# Generated by Django 4.1.2 on 2023-07-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genedata_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domains",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="domains",
            name="domainID",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
