# Generated by Django 4.1.2 on 2023-07-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genedata_api", "0002_domains_id_alter_domains_domainid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domains",
            name="id",
        ),
        migrations.AlterField(
            model_name="domains",
            name="domainID",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
